version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  reviewers:
  - bourque
  assignees:
  - bourque
