name: exo-bespin
channels:
  - defaults
dependencies:
  - boto3=1.9.66
  - jupyter=1.0.0
  - numpy=1.18.5
  - paramiko=2.7.1
  - pip=20.1.1
  - python=3.7.7
  - scp=0.13.2
  - pip:
    - awscli
    - corner==2.1.0
    - juliet==2.0.25
    - platon==4.0