name: exo-bespin
channels:
  - defaults
dependencies:
  - boto3
  - flake8=3.8.4
  - git=2.23.0
  - jupyter=1.0.0
  - numpy=1.19.1
  - paramiko=2.7.1
  - pip=20.1.1
  - pytest=6.1.1
  - python=3.7.7
  - scp=0.13.2
  - pip:
    - awscli
    - batman-package==2.4.6
    - bibtexparser==1.1.0
    - corner==2.1.0
    - platon==4.0
    - git+https://github.com/nespinoza/juliet.git@dev